export const INTEREST_AREAS: string[] = [
  'Tecnologia da Informação',
  'Desenvolvimento de Software',
  'Dados e Inteligência Artificial',
  'Infraestrutura e Cloud',
  'Segurança da Informação',
  'Comercial e Vendas',
  'Marketing e Comunicação',
  'Design e Experiência do Usuário',
  'Recursos Humanos e Pessoas',
  'Financeiro e Controladoria',
  'Jurídico e Compliance',
  'Operações e Processos',
  'Logística e Supply Chain',
  'Engenharia e Projetos',
  'Produto e Inovação',
  'Atendimento ao Cliente e Sucesso do Cliente',
  'Administrativo e Secretariado',
  'Saúde e Bem-estar',
  'Educação e Treinamento',
  'Comunicação e Relações Públicas',
  'Contabilidade e Auditoria',
  'Compras e Suprimentos',
  'Qualidade e Processos',
  'Sustentabilidade e ESG',
  'Franquias e Expansão',
];

export interface RoleGroup {
  label: string;
  items: string[];
}

export const ROLE_GROUPS: RoleGroup[] = [
  {
    label: 'Estágio',
    items: [
      'Estágio em Desenvolvimento de Software',
      'Estágio em Dados e Análise',
      'Estágio em Marketing',
      'Estágio em Recursos Humanos',
      'Estágio em Financeiro',
      'Estágio em Operações',
      'Estágio em Design',
      'Estágio em Jurídico',
      'Estágio em Comercial',
      'Estágio em Engenharia',
      'Estágio em Administrativo',
      'Estágio em Comunicação',
    ],
  },
  {
    label: 'Analista / Especialista',
    items: [
      'Desenvolvedor Front-end Júnior',
      'Desenvolvedor Front-end Pleno',
      'Desenvolvedor Front-end Sênior',
      'Desenvolvedor Back-end Júnior',
      'Desenvolvedor Back-end Pleno',
      'Desenvolvedor Back-end Sênior',
      'Desenvolvedor Full Stack Júnior',
      'Desenvolvedor Full Stack Pleno',
      'Desenvolvedor Full Stack Sênior',
      'Desenvolvedor Mobile (iOS / Android)',
      'Engenheiro de Dados Júnior',
      'Engenheiro de Dados Pleno',
      'Engenheiro de Dados Sênior',
      'Analista de Dados',
      'Cientista de Dados',
      'Analista de Business Intelligence (BI)',
      'Analista de Segurança da Informação',
      'Analista de Infraestrutura',
      'Analista de Suporte Técnico',
      'Analista de Marketing',
      'Analista de Marketing Digital',
      'Especialista em SEO / SEM',
      'Analista de Conteúdo / Redator',
      'Analista de RH',
      'Analista de Recrutamento e Seleção',
      'Analista de Treinamento e Desenvolvimento',
      'Analista Financeiro',
      'Analista de Controladoria',
      'Analista de Contabilidade',
      'Analista Fiscal',
      'Analista de Compras',
      'Analista de Logística',
      'Analista de Operações',
      'Analista de Qualidade',
      'Analista Jurídico',
      'Analista Comercial',
      'Analista de Sucesso do Cliente (CS)',
      'Designer de Produto (UX/UI)',
      'Designer Gráfico',
      'Assistente Administrativo',
      'Auxiliar de Atendimento',
    ],
  },
  {
    label: 'Coordenador / Gerente',
    items: [
      'Coordenador de TI',
      'Coordenador de Marketing',
      'Coordenador de RH',
      'Coordenador Financeiro',
      'Coordenador de Operações',
      'Coordenador de Projetos',
      'Coordenador Comercial',
      'Coordenador de Logística',
      'Coordenador de Qualidade',
      'Gerente de Produto',
      'Gerente de Engenharia',
      'Gerente de Marketing',
      'Gerente de RH',
      'Gerente Financeiro',
      'Gerente Comercial',
      'Gerente de Operações',
      'Gerente de Sucesso do Cliente',
      'Gerente de Projetos',
      'Gerente de Logística',
      'Gerente de TI',
    ],
  },
  {
    label: 'Liderança Sênior / Especialista',
    items: [
      'Tech Lead',
      'Líder de Dados',
      'Arquiteto de Software',
      'Engenheiro de Machine Learning',
      'DevOps / SRE',
      'Head de Produto',
      'Head de Marketing',
      'Head de Pessoas',
      'Head de Vendas',
      'Head de Operações',
      'Head de Engenharia',
      'Head de Dados',
      'Product Manager (PM)',
      'Scrum Master',
      'Agile Coach',
      'Business Partner de RH (HRBP)',
      'Key Account Manager (KAM)',
    ],
  },
  {
    label: 'Diretoria / C-Level',
    items: [
      'Diretor de Tecnologia (CTO)',
      'Diretor de Produto (CPO)',
      'Diretor de Marketing (CMO)',
      'Diretor de Pessoas (CHRO)',
      'Diretor Financeiro (CFO)',
      'Diretor de Operações (COO)',
      'Diretor Comercial (CSO)',
      'Diretor Jurídico (CLO)',
      'CEO / Fundador',
      'Sócio / Consultor Independente',
    ],
  },
];

export const ALL_ROLES: string[] = ROLE_GROUPS.flatMap((g) => g.items);

export const OTHER_OPTION = 'Outros';
