export const OTHER_OPTION = 'Outros';

// Mapping: each area of interest -> list of corresponding roles
export const ROLES_BY_AREA: Record<string, string[]> = {
  'Tecnologia da Informação': [
    'Analista de TI Júnior',
    'Analista de TI Pleno',
    'Analista de TI Sênior',
    'Coordenador de TI',
    'Gerente de TI',
    'Head de TI',
    'Diretor de TI (CTO)',
  ],
  'Desenvolvimento de Software': [
    'Desenvolvedor Front-end Júnior',
    'Desenvolvedor Front-end Pleno',
    'Desenvolvedor Front-end Sênior',
    'Desenvolvedor Back-end Júnior',
    'Desenvolvedor Back-end Pleno',
    'Desenvolvedor Back-end Sênior',
    'Desenvolvedor Full Stack Júnior',
    'Desenvolvedor Full Stack Pleno',
    'Desenvolvedor Full Stack Sênior',
    'Desenvolvedor Mobile (iOS/Android)',
    'Tech Lead',
    'Arquiteto de Software',
    'Engenheiro de Software Sênior',
  ],
  'Dados e Inteligência Artificial': [
    'Analista de Dados Júnior',
    'Analista de Dados Pleno',
    'Analista de Dados Sênior',
    'Engenheiro de Dados Júnior',
    'Engenheiro de Dados Pleno',
    'Engenheiro de Dados Sênior',
    'Cientista de Dados',
    'Analista de BI',
    'Engenheiro de Machine Learning',
    'Líder de Dados',
    'Head de Dados',
  ],
  'Infraestrutura e Cloud': [
    'Analista de Infraestrutura Júnior',
    'Analista de Infraestrutura Pleno',
    'Analista de Infraestrutura Sênior',
    'DevOps / SRE Júnior',
    'DevOps / SRE Pleno',
    'DevOps / SRE Sênior',
    'Arquiteto de Cloud',
    'Coordenador de Infraestrutura',
    'Gerente de Infraestrutura',
  ],
  'Segurança da Informação': [
    'Analista de Segurança da Informação Júnior',
    'Analista de Segurança da Informação Pleno',
    'Analista de Segurança da Informação Sênior',
    'Especialista em Segurança da Informação',
    'Arquiteto de Segurança',
    'Coordenador de Segurança',
    'Gerente de Segurança da Informação',
  ],
  'Comercial e Vendas': [
    'Assistente Comercial',
    'Analista Comercial',
    'Representante de Vendas',
    'Executivo de Contas (AE)',
    'Business Development Representative (BDR)',
    'Sales Development Representative (SDR)',
    'Key Account Manager (KAM)',
    'Coordenador Comercial',
    'Gerente Comercial',
    'Head de Vendas',
    'Diretor Comercial (CSO)',
  ],
  'Marketing e Comunicação': [
    'Assistente de Marketing',
    'Analista de Marketing Júnior',
    'Analista de Marketing Pleno',
    'Analista de Marketing Sênior',
    'Analista de Marketing Digital',
    'Especialista em SEO / SEM',
    'Analista de Mídia Paga',
    'Coordenador de Marketing',
    'Gerente de Marketing',
    'Head de Marketing',
    'Diretor de Marketing (CMO)',
  ],
  'Design e Experiência do Usuário': [
    'Designer Gráfico Júnior',
    'Designer Gráfico Pleno',
    'Designer Gráfico Sênior',
    'Designer de Produto (UX/UI) Júnior',
    'Designer de Produto (UX/UI) Pleno',
    'Designer de Produto (UX/UI) Sênior',
    'UX Researcher',
    'Motion Designer',
    'Coordenador de Design',
    'Head de Design',
  ],
  'Recursos Humanos e Pessoas': [
    'Assistente de RH',
    'Analista de RH Júnior',
    'Analista de RH Pleno',
    'Analista de RH Sênior',
    'Analista de Recrutamento e Seleção',
    'Analista de Treinamento e Desenvolvimento',
    'Business Partner de RH (HRBP)',
    'Coordenador de RH',
    'Gerente de RH',
    'Head de Pessoas',
    'Diretor de Pessoas (CHRO)',
  ],
  'Financeiro e Controladoria': [
    'Assistente Financeiro',
    'Analista Financeiro Júnior',
    'Analista Financeiro Pleno',
    'Analista Financeiro Sênior',
    'Analista de Controladoria',
    'Analista de FP&A',
    'Coordenador Financeiro',
    'Gerente Financeiro',
    'Head de Finanças',
    'Diretor Financeiro (CFO)',
  ],
  'Jurídico e Compliance': [
    'Estagiário Jurídico',
    'Assistente Jurídico',
    'Analista Jurídico Júnior',
    'Analista Jurídico Pleno',
    'Analista Jurídico Sênior',
    'Advogado Júnior',
    'Advogado Pleno',
    'Advogado Sênior',
    'Analista de Compliance',
    'Coordenador Jurídico',
    'Gerente Jurídico',
    'Diretor Jurídico (CLO)',
  ],
  'Operações e Processos': [
    'Assistente de Operações',
    'Analista de Operações Júnior',
    'Analista de Operações Pleno',
    'Analista de Operações Sênior',
    'Analista de Processos',
    'Coordenador de Operações',
    'Gerente de Operações',
    'Head de Operações',
    'Diretor de Operações (COO)',
  ],
  'Logística e Supply Chain': [
    'Assistente de Logística',
    'Analista de Logística Júnior',
    'Analista de Logística Pleno',
    'Analista de Logística Sênior',
    'Analista de Supply Chain',
    'Coordenador de Logística',
    'Coordenador de Supply Chain',
    'Gerente de Logística',
    'Gerente de Supply Chain',
    'Head de Logística',
  ],
  'Engenharia e Projetos': [
    'Estagiário de Engenharia',
    'Engenheiro Júnior',
    'Engenheiro Pleno',
    'Engenheiro Sênior',
    'Analista de Projetos',
    'Gerente de Projetos',
    'Coordenador de Engenharia',
    'Diretor de Engenharia',
  ],
  'Produto e Inovação': [
    'Analista de Produto Júnior',
    'Analista de Produto Pleno',
    'Analista de Produto Sênior',
    'Product Manager (PM)',
    'Senior Product Manager',
    'Product Owner (PO)',
    'Scrum Master',
    'Agile Coach',
    'Head de Produto',
    'Diretor de Produto (CPO)',
  ],
  'Atendimento ao Cliente e Sucesso do Cliente': [
    'Assistente de Atendimento',
    'Analista de Suporte',
    'Analista de Sucesso do Cliente (CS) Júnior',
    'Analista de Sucesso do Cliente (CS) Pleno',
    'Analista de Sucesso do Cliente (CS) Sênior',
    'Customer Success Manager (CSM)',
    'Coordenador de Atendimento',
    'Gerente de Sucesso do Cliente',
    'Head de Customer Success',
  ],
  'Administrativo e Secretariado': [
    'Auxiliar Administrativo',
    'Assistente Administrativo',
    'Assistente Executivo',
    'Secretária Executiva',
    'Analista Administrativo',
    'Coordenador Administrativo',
    'Gerente Administrativo',
  ],
  'Contabilidade e Auditoria': [
    'Auxiliar Contábil',
    'Assistente Contábil',
    'Analista Contábil Júnior',
    'Analista Contábil Pleno',
    'Analista Contábil Sênior',
    'Analista Fiscal',
    'Analista de Auditoria',
    'Coordenador Contábil',
    'Gerente Contábil',
  ],
  'Compras e Suprimentos': [
    'Assistente de Compras',
    'Analista de Compras Júnior',
    'Analista de Compras Pleno',
    'Analista de Compras Sênior',
    'Coordenador de Compras',
    'Gerente de Compras',
    'Head de Suprimentos',
  ],
  'Qualidade e Processos': [
    'Analista de Qualidade Júnior',
    'Analista de Qualidade Pleno',
    'Analista de Qualidade Sênior',
    'Especialista em Qualidade',
    'Coordenador de Qualidade',
    'Gerente de Qualidade',
  ],
  'Sustentabilidade e ESG': [
    'Analista de Sustentabilidade',
    'Analista de ESG',
    'Especialista em ESG',
    'Coordenador de Sustentabilidade',
    'Gerente de ESG',
    'Head de Sustentabilidade',
  ],
  'Comunicação e Relações Públicas': [
    'Assistente de Comunicação',
    'Analista de Comunicação',
    'Analista de Relações Públicas',
    'Redator / Copywriter',
    'Coordenador de Comunicação',
    'Gerente de Comunicação',
  ],
  'Educação e Treinamento': [
    'Instrutor / Facilitador',
    'Analista de Treinamento e Desenvolvimento',
    'Designer Instrucional',
    'Coordenador de Educação Corporativa',
    'Gerente de Treinamento',
    'Head de Educação',
  ],
  'Saúde e Bem-estar': [
    'Analista de Saúde Ocupacional',
    'Técnico de Segurança do Trabalho',
    'Analista de Bem-estar',
    'Coordenador de Saúde e Segurança',
    'Gerente de Saúde Ocupacional',
  ],
  'Franquias e Expansão': [],
};

export const INTEREST_AREAS: string[] = Object.keys(ROLES_BY_AREA);

export const ALL_ROLES: string[] = Array.from(
  new Set(Object.values(ROLES_BY_AREA).flat())
);

// Backwards-compat: kept for any imports relying on grouped roles
export interface RoleGroup {
  label: string;
  items: string[];
}

export const ROLE_GROUPS: RoleGroup[] = INTEREST_AREAS.map((area) => ({
  label: area,
  items: ROLES_BY_AREA[area],
}));

export function getRolesForArea(area?: string | null): string[] {
  if (!area) return [];
  return ROLES_BY_AREA[area] || [];
}
