export interface RequirementCategory {
  id: string;
  label: string;
  items: string[];
}

export const REQUIREMENT_CATEGORIES: RequirementCategory[] = [
  {
    id: 'tecnologia',
    label: 'Informática e Tecnologia',
    items: [
      'Excel Básico',
      'Excel Intermediário',
      'Excel Avançado',
      'Word',
      'PowerPoint',
      'Outlook',
      'Google Workspace (Docs/Sheets/Drive)',
      'Pacote Office Completo',
      'Power BI',
      'ERP',
      'SAP',
      'TOTVS',
      'Oracle',
      'CRM',
      'Canva',
      'Photoshop',
      'Edição de Vídeo',
      'JavaScript',
      'TypeScript',
      'Python',
      'Java',
      'C#',
      'C++',
      'PHP',
      'Ruby',
      'Go',
      'Kotlin',
      'Swift',
      'SQL',
      'HTML/CSS',
      'React',
      'Node.js',
    ],
  },
  {
    id: 'habilitacao',
    label: 'Habilitação e Veículos',
    items: [
      'CNH A (Moto)',
      'CNH B (Carro)',
      'CNH C (Caminhão)',
      'CNH D (Ônibus)',
      'CNH E (Carreta)',
      'CNH AB',
      'Veículo Próprio',
      'Moto Própria',
      'Disponibilidade para Dirigir',
    ],
  },
  {
    id: 'idiomas',
    label: 'Idiomas',
    items: [
      'Inglês Básico',
      'Inglês Intermediário',
      'Inglês Avançado',
      'Inglês Fluente',
      'Espanhol Básico',
      'Espanhol Intermediário',
      'Espanhol Avançado',
      'Espanhol Fluente',
      'Mandarim',
      'Francês',
      'Alemão',
      'Italiano',
      'Libras',
    ],
  },
  {
    id: 'escolaridade',
    label: 'Escolaridade',
    items: [
      'Ensino Fundamental Completo',
      'Ensino Médio Incompleto',
      'Ensino Médio Completo',
      'Ensino Técnico',
      'Cursando Superior',
      'Superior Completo',
      'Pós-Graduação / MBA',
      'Mestrado',
      'Doutorado',
    ],
  },
  {
    id: 'soft-skills',
    label: 'Habilidades Comportamentais (Soft Skills)',
    items: [
      'Comunicação Clara',
      'Trabalho em Equipe',
      'Proatividade',
      'Organização',
      'Pontualidade',
      'Atenção aos Detalhes',
      'Resiliência',
      'Inteligência Emocional',
      'Facilidade para Aprender',
      'Orientação a Resultados',
      'Pensamento Crítico',
      'Criatividade',
      'Capacidade de Negociação',
      'Liderança',
      'Gestão do Tempo',
      'Foco no Cliente',
      'Flexibilidade / Adaptabilidade',
    ],
  },
  {
    id: 'certificacoes',
    label: 'Certificações e Cursos',
    items: [
      'NR-10 (Elétrica)',
      'NR-12 (Máquinas e Equipamentos)',
      'NR-35 (Trabalho em Altura)',
      'NR-20 (Líquidos Combustíveis)',
      'CREA / CRM / CRC / OAB (conselho profissional)',
      'ANVISA (Vigilância Sanitária)',
      'FISPQ / Manuseio de Produtos Químicos',
      'Certificação Lean / Six Sigma',
      'Certificação em Gestão de Projetos (PMI/PMP)',
      'Certificação de Segurança do Trabalho',
      'Curso de Primeiros Socorros',
      'MOPP (Transporte de Produtos Perigosos)',
    ],
  },
  {
    id: 'disponibilidade',
    label: 'Disponibilidade',
    items: [
      'Disponibilidade para Viagens',
      'Disponibilidade para Horas Extras',
      'Disponibilidade nos Finais de Semana',
      'Disponibilidade para Trabalho em Turnos',
      'Disponibilidade para Trabalho Noturno',
      'Disponibilidade Imediata',
      'Disponibilidade para Trabalho Presencial',
      'Disponibilidade para Trabalho Remoto / Home Office',
      'Disponibilidade para Trabalho Híbrido',
    ],
  },
];
