project_id = "herfafjqjvlaehabfxss"

[functions.create-tenant-user]
verify_jwt = false

[functions.send-candidate-status-email]
verify_jwt = false

[functions.generate-job-description]
verify_jwt = false

[functions.jarvis-chat]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true
