project_id = "herfafjqjvlaehabfxss"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.create-tenant-user]
    verify_jwt = false
  [functions.generate-job-description]
    verify_jwt = false
  [functions.jarvis-chat]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.send-candidate-status-email]
    verify_jwt = false
  [functions.send-transactional-email]
    verify_jwt = false
  [functions.preview-transactional-email]
    verify_jwt = false
  [functions.handle-email-unsubscribe]
    verify_jwt = false
  [functions.handle-email-suppression]
    verify_jwt = false
  [functions.send-job-approval-email]
    verify_jwt = true
